# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main_Window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 502)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.SearchBox = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchBox.setObjectName("SearchBox")
        self.gridLayout.addWidget(self.SearchBox, 0, 1, 1, 2)
        self.AddPassButton = QtWidgets.QPushButton(self.centralwidget)
        self.AddPassButton.setObjectName("AddPassButton")
        self.gridLayout.addWidget(self.AddPassButton, 0, 3, 1, 1)
        self.EditCheckbox = QtWidgets.QCheckBox(self.centralwidget)
        self.EditCheckbox.setObjectName("EditCheckbox")
        self.gridLayout.addWidget(self.EditCheckbox, 2, 3, 1, 1)
        self.ShowCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.ShowCheckBox.setObjectName("ShowCheckBox")
        self.gridLayout.addWidget(self.ShowCheckBox, 1, 3, 1, 1)
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setObjectName("SearchButton")
        self.gridLayout.addWidget(self.SearchButton, 0, 0, 1, 1)
        self.PasswordsWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.PasswordsWidget.setAnimated(False)
        self.PasswordsWidget.setObjectName("PasswordsWidget")
        self.gridLayout.addWidget(self.PasswordsWidget, 1, 2, 4, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.CategoriesWidget = QtWidgets.QListWidget(self.centralwidget)
        self.CategoriesWidget.setObjectName("CategoriesWidget")
        self.verticalLayout_4.addWidget(self.CategoriesWidget)
        self.AddCatagoryBox = QtWidgets.QLineEdit(self.centralwidget)
        self.AddCatagoryBox.setText("")
        self.AddCatagoryBox.setObjectName("AddCatagoryBox")
        self.verticalLayout_4.addWidget(self.AddCatagoryBox)
        self.AddCategory = QtWidgets.QPushButton(self.centralwidget)
        self.AddCategory.setObjectName("AddCategory")
        self.verticalLayout_4.addWidget(self.AddCategory)
        self.DeleteCategory = QtWidgets.QPushButton(self.centralwidget)
        self.DeleteCategory.setObjectName("DeleteCategory")
        self.verticalLayout_4.addWidget(self.DeleteCategory)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 0, 4, 2)
        self.SettingsButton = QtWidgets.QPushButton(self.centralwidget)
        self.SettingsButton.setObjectName("SettingsButton")
        self.gridLayout.addWidget(self.SettingsButton, 4, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_2)
        self.menuFile.addAction(self.actionOpen_file)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddPassButton.setText(_translate("MainWindow", "Add Password"))
        self.EditCheckbox.setText(_translate("MainWindow", "Edit"))
        self.ShowCheckBox.setText(_translate("MainWindow", "Show"))
        self.SearchButton.setText(_translate("MainWindow", "Search"))
        self.PasswordsWidget.headerItem().setText(0, _translate("MainWindow", "Tag"))
        self.PasswordsWidget.headerItem().setText(1, _translate("MainWindow", "URL"))
        self.PasswordsWidget.headerItem().setText(2, _translate("MainWindow", "User Name"))
        self.PasswordsWidget.headerItem().setText(3, _translate("MainWindow", "Password"))
        self.label.setText(_translate("MainWindow", "                Catagory"))
        self.AddCatagoryBox.setPlaceholderText(_translate("MainWindow", "Add Catagory"))
        self.AddCategory.setText(_translate("MainWindow", "Add Catagory"))
        self.DeleteCategory.setText(_translate("MainWindow", "Delete Catagory"))
        self.SettingsButton.setText(_translate("MainWindow", "Settings"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_2.setText(_translate("MainWindow", "Save as"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
